plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "0.3.3"
    id 'dev._100media.gradleutils'
}


dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.1:2023.07.09@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly project(":Common")
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.2")))
    modImplementation "software.bernie.geckolib:geckolib-fabric-1.20.1:${geckolib_version}"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"
    include "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"
}

loom {

    if (project.hasProperty('fabric_aws_enabled') && project.findProperty('fabric_aws_enabled').toBoolean()) {
        accessWidenerPath = project(":Common").file("src/main/resources/accesstransformers.accesswidener")
    }
    runs {
        client {
            client()
            vmArgs("-XX:+AllowEnhancedClassRedefinition")
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("client")
        }
        server {
            server()
            vmArgs("-XX:+AllowEnhancedClassRedefinition")
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("server")
        }
    }
    mixin {
        defaultRefmapName = "${mod_id}.refmap.json"
    }
}

publishMods {
    if(publishFabric) {
        file = remapJar.archiveFile
        changelog = project(":Common").file("changelog.md").text
        type = STABLE
        modLoaders.add("fabric")
        displayName = "${mod_name}-${minecraft_version}-[Fabric]-${project.property('version')}"
        if (curseforge_publishing_enabled.toBoolean()) {
            curseforge {
                projectId = curseforge_project_id
                accessToken = curseforge_token
                minecraftVersions.add(minecraft_version)
            }
        }
        if (modrinth_publishing_enabled.toBoolean()) {
            modrinth {
                accessToken = modrinth_token
                projectId = modrinth_project_id
                minecraftVersions.add(minecraft_version)
            }
        }
    }
}
